
trigger: none

pool:
  name: pif-cloud    # name of agent pool, update the name and uncomment

resources:
  repositories:
    - repository: pif-devops-non-prod  # PIF yaml templates for non-prod environment
      type: git
      ref: github-fix                                 
      name: 'BOS Process Integration Framework/pif-devops-pipelines'  

    - repository: pif-dev              
      type: git
      ref: release
      name: 'BOS Process Integration Framework/pif-dev'

variables:
- name: releaseversion
  value: '1.0.0'
- template: vars.yml  # variable template

stages:
#------------------------------------------------------------------------------
# Deploy to Test
#------------------------------------------------------------------------------
- stage: DeployToTest
  displayName: Deploy to Test
  jobs:
    - template: pipelines/helm_cd_deploy.yml@pif-devops-non-prod
      parameters:
        Env: 'test'
        Project: 'BOS Process Integration Framework'  
        Pipeline: 'BOS Process Integration Framework-CI (2)'  
        DeployScriptSubPath: 'deployscripts/v2'  
        BuildId: $(BuildNum)
        timeoutInMinutes: '2'
